version: '3'
services:
  web:
    build: .
    expose:
      - "5000"
    environment:
      - SERVICE_PORTS=5000
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - web
    depends_on:
      - web
    ports:
     - '5000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
